spring.datasource.url=postgresql://krishna:ZouqC0WEapbTvYMTxgOuGVwa02B4P83M@dpg-d0a4q80gjchc73bgvpn0-a/unitybank
spring.datasource.username=krishna
spring.datasource.password=ZouqC0WEapbTvYMTxgOuGVwa02B4P83M
spring.datasource.driver-class-name=org.postgresql.Driver

# spring.datasource.username=root
# spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway?serverTimezone=UTC
# spring.datasource.password=DQLtuSIdLzhMjhTUKjXHwEJkKbqNXZiB
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false